/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.MySQL;

/**
 *
 * @author mamet
 */
public class AttendancePanel extends javax.swing.JPanel {

    /**
     * Creates new form enrollmentsPanel
     */
    public AttendancePanel() {
        initComponents();
        loadAttendanceData();
    }
    
    private void loadAttendanceData() {
        try {
            ResultSet attendanceData = MySQL.executeSearch("SELECT * FROM `attendance` "
                    + "INNER JOIN `student_enrollment` ON `attendance`.`student_class_enrollment_id` = `student_enrollment`.`student_enrollment_id` "
                    + "INNER JOIN `student` ON `student_enrollment`.`student_s_no` = `student`.`s_no` "
                    + "INNER JOIN `class` ON `student_enrollment`.`class_class_no` = `class`.class_no "
                    + "INNER JOIN `teacher_has_subject` ON `class`.`teacher_has_subject_id` = `teacher_has_subject`.`teacher_subject_id` "
                    + "INNER JOIN `teacher` ON `teacher_has_subject`.`teacher_t_no` = `teacher`.`t_no` "
                    + "INNER JOIN `subject` ON `teacher_has_subject`.`subject_sub_no` = `subject`.`sub_no`");
            DefaultTableModel attendanceTable = (DefaultTableModel) attendanceDataTable.getModel();
            attendanceTable.setRowCount(0);
            
            while (attendanceData.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(attendanceData.getString("student.first_name") + " " + attendanceData.getString("student.last_name"));
                vector.add(attendanceData.getString("attendance.date"));
                vector.add(attendanceData.getString("subject.name"));
                vector.add(attendanceData.getString("teacher.first_name") + " " + attendanceData.getString("teacher.last_name"));
                
                attendanceTable.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        markStudentEmailField = new javax.swing.JTextField();
        markClassIdField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        markAttendanceButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceDataTable = new javax.swing.JTable();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Student Email");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Class ID");

        markAttendanceButton.setBackground(new java.awt.Color(0, 102, 0));
        markAttendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        markAttendanceButton.setText("Mark Attendance");
        markAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAttendanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(markAttendanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addComponent(markStudentEmailField)
                    .addComponent(markClassIdField))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markStudentEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markClassIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(markAttendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mark Attendance", jPanel1);

        attendanceDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Date", "Subject", "Teacher Name"
            }
        ));
        jScrollPane1.setViewportView(attendanceDataTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void markAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAttendanceButtonActionPerformed
        String studentEmail = markStudentEmailField.getText();
        String classId = markClassIdField.getText();
        
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String attendDate = dateFormat.format(date);
        
        try {
            ResultSet enrollResult = MySQL.executeSearch("SELECT * FROM `student_enrollment` "
                    + "INNER JOIN `student` ON `student_enrollment`.`student_s_no` = `student`.`s_no` "
                    + "WHERE `student`.`email`='" + studentEmail + "' AND `student_enrollment`.`class_class_no`='" + classId + "'");
            if (enrollResult.next()) {
                String enrollId = enrollResult.getString("student_enrollment.student_enrollment_id");
                
                MySQL.executeIUD("INSERT INTO `attendance`(`date`,`student_class_enrollment_id`) VALUES('" + attendDate + "','" + enrollId + "')");
                JOptionPane.showMessageDialog(this, "Attendance Marked successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadAttendanceData();
                markStudentEmailField.setText("");
                markClassIdField.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Enrollment not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_markAttendanceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendanceDataTable;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton markAttendanceButton;
    private javax.swing.JTextField markClassIdField;
    private javax.swing.JTextField markStudentEmailField;
    // End of variables declaration//GEN-END:variables
}
