/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author mamet
 */
public class DashboardWindow extends javax.swing.JFrame {

    /**
     * Creates new form dashboardWindow
     */
    public DashboardWindow() {
        initComponents();
        updatePanel(new RegistrationsPanel());
        registrationsButton.setBackground(Color.red);
    }
    
    private void updatePanel(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
        resetBtnColors();
    }
    
    private void resetBtnColors() {
        registrationsButton.setBackground(Color.DARK_GRAY);
        enrollmentsButton.setBackground(Color.DARK_GRAY);
        attendanceButton.setBackground(Color.DARK_GRAY);
        paymentsButton.setBackground(Color.DARK_GRAY);
        managementButton.setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navPanel = new javax.swing.JPanel();
        registrationsButton = new javax.swing.JButton();
        enrollmentsButton = new javax.swing.JButton();
        attendanceButton = new javax.swing.JButton();
        paymentsButton = new javax.swing.JButton();
        managementButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Adyapana Institute");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(946, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        navPanel.setPreferredSize(new java.awt.Dimension(250, 620));
        navPanel.setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        registrationsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrationsButton.setText("Registrations");
        registrationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationsButtonActionPerformed(evt);
            }
        });
        navPanel.add(registrationsButton);

        enrollmentsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enrollmentsButton.setText("Enrollments");
        enrollmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentsButtonActionPerformed(evt);
            }
        });
        navPanel.add(enrollmentsButton);

        attendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        attendanceButton.setText("Attendance");
        attendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceButtonActionPerformed(evt);
            }
        });
        navPanel.add(attendanceButton);

        paymentsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paymentsButton.setText("Payments");
        paymentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsButtonActionPerformed(evt);
            }
        });
        navPanel.add(paymentsButton);

        managementButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        managementButton.setText("Management");
        managementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementButtonActionPerformed(evt);
            }
        });
        navPanel.add(managementButton);

        getContentPane().add(navPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationsButtonActionPerformed
        updatePanel(new RegistrationsPanel());
        registrationsButton.setBackground(Color.red);
    }//GEN-LAST:event_registrationsButtonActionPerformed

    private void enrollmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentsButtonActionPerformed
        updatePanel(new EnrollmentsPanel());
        enrollmentsButton.setBackground(Color.red);
    }//GEN-LAST:event_enrollmentsButtonActionPerformed

    private void attendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceButtonActionPerformed
        updatePanel(new AttendancePanel());
        attendanceButton.setBackground(Color.red);
    }//GEN-LAST:event_attendanceButtonActionPerformed

    private void paymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsButtonActionPerformed
        updatePanel(new PaymentsPanel());
        paymentsButton.setBackground(Color.red);
    }//GEN-LAST:event_paymentsButtonActionPerformed

    private void managementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementButtonActionPerformed
        updatePanel(new ManagementPanel());
        managementButton.setBackground(Color.red);
    }//GEN-LAST:event_managementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendanceButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton enrollmentsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton managementButton;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton paymentsButton;
    private javax.swing.JButton registrationsButton;
    // End of variables declaration//GEN-END:variables
}
