/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.MySQL;

/**
 *
 * @author mamet
 */
public class SubjectsPanel extends javax.swing.JPanel {

    /**
     * Creates new form attendancePanel
     */
    public SubjectsPanel() {
        initComponents();
        generateSubjectNo();
        loadSubjectData("");
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        manageSubNameField.setEditable(false);
        managePriceField.setEditable(false);
    }

    private void generateSubjectNo() {
        try {
            ResultSet subNo = MySQL.executeSearch("SELECT COUNT(`sub_no`) AS subno FROM `subject`");
            if (subNo.next()) {
                int usedNo = subNo.getInt("subno");
                int newNo = usedNo + 1;
                regSubjectNoField.setText(String.valueOf(newNo));
            } else {
                regSubjectNoField.setText("1");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearAddFields() {
        generateSubjectNo();
        regSubjectNameField.setText("");
        regPriceField.setText("");
    }

    private void clearManageFields() {
        manageSubNoField.setText("");
        manageSubNameField.setText("");
        managePriceField.setText("");
        manageSearchButton.setEnabled(true);
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        manageSubNoField.setEditable(true);
        managePriceField.setEditable(false);
    }

    private void loadSubjectData(String subId) {
        if (!subId.isBlank()) {
            try {
                ResultSet subjectData = MySQL.executeSearch("SELECT * FROM `subject` WHERE `sub_no`='" + subId + "'");
                DefaultTableModel subTable = (DefaultTableModel) subjectDataTable.getModel();
                subTable.setRowCount(0);

                while (subjectData.next()) {
                    Vector<String> vector = new Vector<>();
                    vector.add(subjectData.getString("sub_no"));
                    vector.add(subjectData.getString("name"));
                    vector.add(subjectData.getString("price"));

                    subTable.addRow(vector);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                ResultSet subjectData = MySQL.executeSearch("SELECT * FROM `subject`");
                DefaultTableModel subTable = (DefaultTableModel) subjectDataTable.getModel();
                subTable.setRowCount(0);

                while (subjectData.next()) {
                    Vector<String> vector = new Vector<>();
                    vector.add(subjectData.getString("sub_no"));
                    vector.add(subjectData.getString("name"));
                    vector.add(subjectData.getString("price"));

                    subTable.addRow(vector);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regSubjectNoField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regSubjectNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        regPriceField = new javax.swing.JTextField();
        addSubjectButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectDataTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        manageSubNameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        manageSubNoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        managePriceField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        manageSearchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Subject Number");

        regSubjectNoField.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Subject Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Price");

        addSubjectButton.setBackground(new java.awt.Color(0, 102, 0));
        addSubjectButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSubjectButton.setText("Add Subject");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh-24px.png"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regSubjectNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton))
                    .addComponent(jLabel2)
                    .addComponent(addSubjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regSubjectNameField)
                    .addComponent(regPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(regSubjectNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regSubjectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel1);

        subjectDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject No", "Subject Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subjectDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjectDataTable);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Subject No");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Price");

        updateButton.setBackground(new java.awt.Color(0, 0, 153));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(102, 0, 0));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        manageSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search-24px.png"))); // NOI18N
        manageSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSearchButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(manageSubNameField)
                    .addComponent(jLabel9)
                    .addComponent(managePriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageSubNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manageSubNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(manageSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageSubNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(managePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        generateSubjectNo();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        String subNo = regSubjectNoField.getText();
        String subName = regSubjectNameField.getText();
        String price = regPriceField.getText();

        if (subName.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter subject name", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (price.isBlank()) {
            JOptionPane.showMessageDialog(this, "Enter price", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                MySQL.executeIUD("INSERT INTO `subject`(`sub_no`,`name`,`price`) VALUES('" + subNo + "','" + subName + "','" + price + "')");
                JOptionPane.showMessageDialog(this, "Subject Registered Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearAddFields();
                loadSubjectData("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_addSubjectButtonActionPerformed

    private void manageSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSearchButtonActionPerformed
        String subNo = manageSubNoField.getText();
        loadSubjectData(subNo);
    }//GEN-LAST:event_manageSearchButtonActionPerformed

    private void subjectDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectDataTableMouseClicked
        if (evt.getClickCount() == 2) {
            int rowIndex = subjectDataTable.getSelectedRow();
            TableModel subjectTable = subjectDataTable.getModel();
            String subNo = String.valueOf(subjectTable.getValueAt(rowIndex, 0));

            if (subNo != null && !subNo.isBlank()) {
                updateButton.setEnabled(true);
                deleteButton.setEnabled(true);
                manageSearchButton.setEnabled(false);
                manageSubNoField.setEditable(false);
                manageSubNameField.setEditable(false);
                managePriceField.setEditable(true);

                try {
                    ResultSet result = MySQL.executeSearch("SELECT * FROM `subject` WHERE `sub_no`='" + subNo + "'");
                    if (result.next()) {
                        manageSubNoField.setText(subNo);
                        manageSubNameField.setText(result.getString("name"));
                        managePriceField.setText(result.getString("price"));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_subjectDataTableMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearManageFields();
        loadSubjectData("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String subNo = manageSubNoField.getText();
        String price = managePriceField.getText();

        try {
            MySQL.executeIUD("UPDATE `subject` SET `price`='" + price + "' WHERE `sub_no`='" + subNo + "'");
            JOptionPane.showMessageDialog(this, "Subject Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearManageFields();
            loadSubjectData("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String subNo = manageSubNoField.getText();

        try {
            MySQL.executeIUD("DELETE FROM `subject` WHERE `sub_no`='" + subNo + "'");
            JOptionPane.showMessageDialog(this, "Subject Removed Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadSubjectData("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField managePriceField;
    private javax.swing.JButton manageSearchButton;
    private javax.swing.JTextField manageSubNameField;
    private javax.swing.JTextField manageSubNoField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField regPriceField;
    private javax.swing.JTextField regSubjectNameField;
    private javax.swing.JTextField regSubjectNoField;
    private javax.swing.JTable subjectDataTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
